Update Lecture-3
Final update to the Lecture-3 document, following style guide guidelines and best coding practices.

diff --git a/Lecture-3 b/Lecture-3
--- a/Lecture-3
+++ b/Lecture-3
@@ -1,31 +1,50 @@
-
-Lecture 3 - 1/25/23 - Outline
-
-
-Basic Linux Commands:
-curl - capture url
-pwd - display the name of the present working directory.
-cd - change directory
-ls - view contents
-mkdir - make directory
-man - manual command, display information regarding other commands
-ssh - secure shell, connecting to remote servers
-less - view text information regarding a file
-cp - copy a file or directory
-mv - move a file or directory
-rm - remove a file or directory
-grep - pattern-matching, prints the lines that match a specified pattern within each file
-| - piping, used to “pipe” the output of one command or program as the input for another command or program
-wc - word count of a specified file (FLAGS -> -l = line count)
-basename - prints the base name (name with no leading or trailing path) of a specified file or directory
-dirname - print the directory path to specified file or directory
-xargs - build and execute command lines from standard input
-cut - remove sections from each line of a file (FLAGS -> -d = delimiter, -f = field)
-sort - sort lines of text files
-uniq - only return unique elements (no repeats)
+#Lecture 3 - 1/25/23 - Outline
 
 
-For Loop Structure:
+###Basic Linux Commands:
+#### Definition
+**curl** - capture url
+#### Definition
+**pwd** - display the name of the present working directory.
+#### Definition
+**cd** - change directory
+#### Definition
+**ls** - view contents
+#### Definition
+**mkdir** - make directory
+#### Definition
+**man** - manual command, display information regarding other commands
+#### Definition
+**ssh** - secure shell, connecting to remote servers
+#### Definition
+**less** - view text information regarding a file
+#### Definition
+**cp** - copy a file or directory
+#### Definition
+**mv** - move a file or directory
+#### Definition
+**rm** - remove a file or directory
+#### Definition
+**grep** - pattern-matching, prints the lines that match a specified pattern within each file
+#### Definition
+**|** - piping, used to “pipe” the output of one command or program as the input for another command or program
+#### Definition
+**wc** - word count of a specified file (FLAGS -> -l = line count)
+#### Definition
+**basename** - prints the base name (name with no leading or trailing path) of a specified file or directory
+#### Definition
+**dirname** - print the directory path to specified file or directory
+#### Definition
+**xargs** - build and execute command lines from standard input
+#### Definition
+**cut** - remove sections from each line of a file (FLAGS -> -d = delimiter, -f = field)
+#### Definition
+**sort** - sort lines of text files
+#### Definition
+**uniq** - only return unique elements (no repeats)
+
+
+###For Loop Structure:
 	for i in {start..end..step}
 	do
 		echo $i
@@ -35,7 +54,7 @@ For Loop Structure:
   by which to iterate the current index at each step.
 
 
-Accessing Variable Values:
+###Accessing Variable Values:
 	To access the values of variables in our commands, we use the dollar sign character, $,
 	followed by the name of our variable.
 	
@@ -48,7 +67,7 @@ Accessing Variable Values:
 	output.
 
 
-Connecting to your Linux Lab Machine:
+###Connecting to your Linux Lab Machine:
 	You will be assigned a local machine at the beginning of the year, and must enter your 
   information according to the below format and enter your password when prompted.
 
@@ -56,7 +75,7 @@ Format:
   YOUR_USERNAME@stlawu.edu@cslinuxlab-YOUR_NUMBER.stlawu.local
 
 
-One-Line Command Format:
+###One-Line Command Format:
 	Commands such as the for loop illustrated above can be executed in one line when 
   utilizing the semicolon character. For example, the following for loops are equivalent:
 
@@ -68,13 +87,13 @@ for f in random
 for f in random; do echo $f; done
 
 
-Manipulating and Accessing files in pwd:
+###Manipulating and Accessing files in pwd:
   You can view the contents of your pwd with the ls command, and you can copy, move or remove any file or directory in the pwd with the 
   commands cp, mv, and rm respectfully. You can also back out a level from your current directory with the command cd .., as well as 
   move to other subdirectories via cd DIR_NAME.
 
 
-For Loop File Globbing:
+###For Loop File Globbing:
 for i in random/*
 	do
 	echo $i
@@ -85,13 +104,13 @@ in which the use of a wildcard character such as an asterisk gets expanded upon 
 files and directories.
 
 
-Using Man for Command Instruction
+###Using Man for Command Instruction
 	The man command is useful for finding information regarding any of the linux 
   commands. This command provides you with the name of the command, formatting,
   uses, and much more helpful information.
 
 
-Pattern-Matching with grep
+###Pattern-Matching with grep
   The pattern matching command grep can be utilized in combination with escape characters to match file names or contents 
   based on the rules specified by the escape characters. For example, including a carat (^) at the beginning of the string 
   following grep will ensure that we pattern match files whose names begin with the specified string. Similarly, we can 
@@ -104,7 +123,7 @@ Pattern-Matching with grep
 Ex) find random | grep ^\\.ac$; output -> files that begin and end with the string “.ac”.
 
 
-Command Substitution
+###Command Substitution
 	Using the same method by which we accessed our values of previously defined 
   variables, we can also run a command and provide it’s output as text in the command 
   line arguments for another command.
@@ -115,7 +134,8 @@ Ex) for i in {0..#(find random | grep ace | wc -l)}
 	done
 
 
-xargs
+#### Definition
+**xargs**
   The xargs command builds and executes command lines from standard input.
 
 Ex) xargs basename | grep ^9; 
@@ -123,10 +143,17 @@ Ex) xargs basename | grep ^9;
   pattern-match the result for names beginning with the character 9.
 
 
-Left to Cover:
-Cut
-Conditional Statement Structure
-Test
-Exit Code $?
-Redirecting Output (Standard and Error)
-Sort and Uniq
+###Conditional Statement Structure
+	Conditionals work by ending the statement with if in reverse (fi).
+Ex) if [ -f $f ]; then do echo $f; fi;
+
+
+###Exit Code
+You can view the exit status of a program’s execution using echo $?
+####$? - Exit code of previously executed program, 0 upon success and failure otherwise.
+
+
+###Redirecting Output (Standard and Error)
+	You can redirect output from a program into a file of your choosing using the greater than symbol.
+Ex) find random > randomfiles.txt
+
